./../rtl/CLKGEN1HZ.v
./../rtl/CLKGEN1K.v
./../rtl/CLOCKVALUE.v
./../rtl/DEBOUNCING.v
./../rtl/DECODE7SEG.v
./../rtl/DIGITALCLOCK.v
./../rtl/LCD_CTRL.v
./../rtl/LCD_DISPLAY.v
./../rtl/LEDCLOCK.v
./../rtl/STOPWATCH.v
./../rtl/TB_TOP.v
./../rtl/TIMER.v
./../rtl/TOP_FPGA.v
./../rtl/TOP.v
./../rtl/TOUCH.v
